In [57]:
# Importando as bibliotecas necess√°rias
import pandas as pd
import numpy as np
import os

In [58]:
os.chdir('C:\\Users\\ana.sales_republica\\Downloads')

In [ ]:
os.listdir()

In [72]:
pd.options.display.float_format = '{:.2f}'.format

In [73]:
df06 = pd.read_excel('pnad_tabelas_graficos.xlsx', sheet_name='Dados6')
df06
#subir com coluna arrendodada, descartar prop

       cor    sexo     esfera        sum  prop    cv  Unnamed: 6
0   Branca   Homem   Estadual  819767.13 23.70  2.65        0.24
1   Branca  Mulher   Estadual  906860.88 26.20  2.63        0.26
2    Negra   Homem   Estadual  867519.80 25.00  2.65        0.25
3    Negra  Mulher   Estadual  826919.62 23.90  2.54        0.24
4    Outra   Homem   Estadual   22760.95  0.70 21.57        0.01
5    Outra  Mulher   Estadual   21873.46  0.60 17.45        0.01
6   Branca   Homem    Federal  543491.98 32.10  3.84        0.32
7   Branca  Mulher    Federal  367190.81 21.70  4.81        0.22
8    Negra   Homem    Federal  515235.87 30.40  3.66        0.30
9    Negra  Mulher    Federal  228679.36 13.50  5.55        0.14
10   Outra   Homem    Federal   20490.96  1.20 21.67        0.01
11   Outra  Mulher    Federal   17629.44  1.00 19.67        0.01
12  Branca   Homem  Municipal  947599.83 13.80  2.28         NaN
13  Branca  Mulher  Municipal 1951554.26 28.50  1.26         NaN
14   Negra   Homem  Municipal 1415888.85 20.60  1.82         NaN
15   Negra  Mulher  Municipal 2465844.47 36.00  0.95         NaN
16   Outra   Homem  Municipal   38062.74  0.60 15.13         NaN
17   Outra  Mulher  Municipal   40037.15  0.60 10.30         NaN

In [74]:
df06 = df06.drop(['Unnamed: 6'], axis=1)

In [75]:
df06

       cor    sexo     esfera        sum  prop    cv
0   Branca   Homem   Estadual  819767.13 23.70  2.65
1   Branca  Mulher   Estadual  906860.88 26.20  2.63
2    Negra   Homem   Estadual  867519.80 25.00  2.65
3    Negra  Mulher   Estadual  826919.62 23.90  2.54
4    Outra   Homem   Estadual   22760.95  0.70 21.57
5    Outra  Mulher   Estadual   21873.46  0.60 17.45
6   Branca   Homem    Federal  543491.98 32.10  3.84
7   Branca  Mulher    Federal  367190.81 21.70  4.81
8    Negra   Homem    Federal  515235.87 30.40  3.66
9    Negra  Mulher    Federal  228679.36 13.50  5.55
10   Outra   Homem    Federal   20490.96  1.20 21.67
11   Outra  Mulher    Federal   17629.44  1.00 19.67
12  Branca   Homem  Municipal  947599.83 13.80  2.28
13  Branca  Mulher  Municipal 1951554.26 28.50  1.26
14   Negra   Homem  Municipal 1415888.85 20.60  1.82
15   Negra  Mulher  Municipal 2465844.47 36.00  0.95
16   Outra   Homem  Municipal   38062.74  0.60 15.13
17   Outra  Mulher  Municipal   40037.15  0.60 10.30

In [76]:
df06['soma_arredondada'] = df06['sum'].round()
df06['soma_arredondada'] = df06['soma_arredondada'].astype(int)
df06

       cor    sexo     esfera        sum  prop    cv  soma_arredondada
0   Branca   Homem   Estadual  819767.13 23.70  2.65            819767
1   Branca  Mulher   Estadual  906860.88 26.20  2.63            906861
2    Negra   Homem   Estadual  867519.80 25.00  2.65            867520
3    Negra  Mulher   Estadual  826919.62 23.90  2.54            826920
4    Outra   Homem   Estadual   22760.95  0.70 21.57             22761
5    Outra  Mulher   Estadual   21873.46  0.60 17.45             21873
6   Branca   Homem    Federal  543491.98 32.10  3.84            543492
7   Branca  Mulher    Federal  367190.81 21.70  4.81            367191
8    Negra   Homem    Federal  515235.87 30.40  3.66            515236
9    Negra  Mulher    Federal  228679.36 13.50  5.55            228679
10   Outra   Homem    Federal   20490.96  1.20 21.67             20491
11   Outra  Mulher    Federal   17629.44  1.00 19.67             17629
12  Branca   Homem  Municipal  947599.83 13.80  2.28            947600
13  Branca  Mulher  Municipal 1951554.26 28.50  1.26           1951554
14   Negra   Homem  Municipal 1415888.85 20.60  1.82           1415889
15   Negra  Mulher  Municipal 2465844.47 36.00  0.95           2465844
16   Outra   Homem  Municipal   38062.74  0.60 15.13             38063
17   Outra  Mulher  Municipal   40037.15  0.60 10.30             40037

In [77]:
df06.dtypes

cor                  object
sexo                 object
esfera               object
sum                 float64
prop                float64
cv                  float64
soma_arredondada      int32
dtype: object

In [78]:
df06.columns

Index(['cor', 'sexo', 'esfera', 'sum', 'prop', 'cv', 'soma_arredondada'], dtype='object')

In [79]:
df06 = df06.rename(columns={'sum':'total',
                        'prop': 'proporcao',
                        'cv':'coeficiente_variacao',
                        'soma_arredondada':'total_arredondado'
                        })
df06

,cor,sexo,esfera,total,proporcao,coeficiente_variacao,total_arredondado
0,Branca,Homem,Estadual,819767.13,23.70,2.65,819767
1,Branca,Mulher,Estadual,906860.88,26.20,2.63,906861
2,Negra,Homem,Estadual,867519.80,25.00,2.65,867520
3,Negra,Mulher,Estadual,826919.62,23.90,2.54,826920
4,Outra,Homem,Estadual,22760.95,0.70,21.57,22761
5,Outra,Mulher,Estadual,21873.46,0.60,17.45,21873
6,Branca,Homem,Federal,543491.98,32.10,3.84,543492
7,Branca,Mulher,Federal,367190.81,21.70,4.81,367191
8,Negra,Homem,Federal,515235.87,30.40,3.66,515236
9,Negra,Mulher,Federal,228679.36,13.50,5.55,228679
10,Outra,Homem,Federal,20490.96,1.20,21.67,20491
11,Outra,Mulher,Federal,17629.44,1.00,19.67,17629
12,Branca,Homem,Municipal,947599.83,13.80,2.28,947600
13,Branca,Mulher,Municipal,1951554.26,28.50,1.26,1951554
14,Negra,Homem,Municipal,1415888.85,20.60,1.82,1415889
15,Negra,Mulher,Municipal,2465844.47,36.00,0.95,2465844
16,Outra,Homem,Municipal,38062.74,0.60,15.13,38063
17,Outra,Mulher,Municipal,40037.15,0.60,10.30,40037

In [81]:
df06.to_csv('dados6.csv', index=False, sep=',')

# Dados7

In [85]:
df07 = pd.read_excel('pnad_tabelas_graficos.xlsx', sheet_name='Dados7')
df07

      cor    sexo       sum  prop    cv
0  Branca   Homem 118410.09 58.30  6.14
1  Branca  Mulher 114057.93 56.40  6.38
2   Negra   Homem  82038.39 40.40  6.88
3   Negra  Mulher  85078.29 42.10  6.63
4   Outra   Homem   2697.37  1.30 41.18
5   Outra  Mulher   2946.58  1.50 37.70

In [87]:
df07['total_arredondado'] = df07['sum'].round()
df07['total_arredondado'] = df07['total_arredondado'].astype(int)
df07

      cor    sexo       sum  prop    cv  total_arredondado
0  Branca   Homem 118410.09 58.30  6.14             118410
1  Branca  Mulher 114057.93 56.40  6.38             114058
2   Negra   Homem  82038.39 40.40  6.88              82038
3   Negra  Mulher  85078.29 42.10  6.63              85078
4   Outra   Homem   2697.37  1.30 41.18               2697
5   Outra  Mulher   2946.58  1.50 37.70               2947

In [88]:
df07.dtypes

cor                   object
sexo                  object
sum                  float64
prop                 float64
cv                   float64
total_arredondado      int32
dtype: object

In [89]:
df07 = df07.rename(columns={'sum':'total',
                        'prop': 'proporcao',
                        'cv':'coeficiente_variacao'
                        })
df07

,cor,sexo,total,proporcao,coeficiente_variacao,total_arredondado
0,Branca,Homem,118410.09,58.30,6.14,118410
1,Branca,Mulher,114057.93,56.40,6.38,114058
2,Negra,Homem,82038.39,40.40,6.88,82038
3,Negra,Mulher,85078.29,42.10,6.63,85078
4,Outra,Homem,2697.37,1.30,41.18,2697
5,Outra,Mulher,2946.58,1.50,37.70,2947

In [90]:
df07.to_csv('dados7.csv', index=False, sep=',')

# Dados8

In [96]:
df08 = pd.read_excel('pnad_tabelas_graficos.xlsx', sheet_name='Dados8')
df08

       cor    sexo            salario        sum  prop    cv
0   Branca   Homem        1 a [0,5SM]   23742.78 12.60 16.41
1   Branca   Homem  [0,5SM]+1 a [1SM]  191383.84 10.50  5.78
2   Branca   Homem    [1SM]+1 a [2SM]  450445.11 13.70  4.26
3   Branca   Homem    [2SM]+1 a [3SM]  408520.87 16.60  4.91
4   Branca   Homem    [3SM]+1 a [5SM]  499566.32 22.20  3.60
5   Branca   Homem   [5SM]+1 a [10SM]  427637.18 32.20  4.64
6   Branca   Homem  [10SM]+1 a [20SM]  253229.02 45.10  6.62
7   Branca   Homem   [20SM]+1 ou mais   51374.66 55.30 12.94
8   Branca  Mulher        1 a [0,5SM]   43178.97 22.90 11.47
9   Branca  Mulher  [0,5SM]+1 a [1SM]  362426.14 19.90  4.78
10  Branca  Mulher    [1SM]+1 a [2SM]  882258.29 26.80  2.76
11  Branca  Mulher    [2SM]+1 a [3SM]  749199.32 30.50  3.10
12  Branca  Mulher    [3SM]+1 a [5SM]  674062.68 30.00  3.28
13  Branca  Mulher   [5SM]+1 a [10SM]  356809.93 26.80  4.94
14  Branca  Mulher  [10SM]+1 a [20SM]  133304.63 23.70  7.13
15  Branca  Mulher   [20SM]+1 ou mais   20705.15 22.30 30.20
16   Negra   Homem        1 a [0,5SM]   39952.92 21.20 12.94
17   Negra   Homem  [0,5SM]+1 a [1SM]  465229.41 25.50  3.62
18   Negra   Homem    [1SM]+1 a [2SM]  794277.18 24.20  2.60
19   Negra   Homem    [2SM]+1 a [3SM]  512167.98 20.80  3.79
20   Negra   Homem    [3SM]+1 a [5SM]  536001.01 23.90  3.19
21   Negra   Homem   [5SM]+1 a [10SM]  316586.44 23.80  4.97
22   Negra   Homem  [10SM]+1 a [20SM]  113534.15 20.20  7.29
23   Negra   Homem   [20SM]+1 ou mais   13199.09 14.20 20.63
24   Negra  Mulher        1 a [0,5SM]   79813.43 42.30  9.57
25   Negra  Mulher  [0,5SM]+1 a [1SM]  782488.56 42.90  2.56
26   Negra  Mulher    [1SM]+1 a [2SM] 1129799.31 34.40  2.09
27   Negra  Mulher    [2SM]+1 a [3SM]  751577.33 30.60  2.95
28   Negra  Mulher    [3SM]+1 a [5SM]  503303.14 22.40  3.52
29   Negra  Mulher   [5SM]+1 a [10SM]  207855.79 15.60  5.79
30   Negra  Mulher  [10SM]+1 a [20SM]   47745.88  8.50 12.76
31   Negra  Mulher   [20SM]+1 ou mais    5390.07  5.80 28.25
32   Outra   Homem        1 a [0,5SM]     292.79  0.20 97.04
33   Outra   Homem  [0,5SM]+1 a [1SM]   13066.36  0.70 24.03
34   Outra   Homem    [1SM]+1 a [2SM]   14774.19  0.40 25.53
35   Outra   Homem    [2SM]+1 a [3SM]   14400.54  0.60 34.76
36   Outra   Homem    [3SM]+1 a [5SM]   14224.73  0.60 30.47
37   Outra   Homem   [5SM]+1 a [10SM]   12280.60  0.90 32.04
38   Outra   Homem  [10SM]+1 a [20SM]   10018.00  1.80 36.33
39   Outra   Homem   [20SM]+1 ou mais    2257.43  2.40 67.89
40   Outra  Mulher        1 a [0,5SM]    1760.60  0.90 58.69
41   Outra  Mulher  [0,5SM]+1 a [1SM]    9671.04  0.50 25.00
42   Outra  Mulher    [1SM]+1 a [2SM]   15384.42  0.50 19.36
43   Outra  Mulher    [2SM]+1 a [3SM]   20689.49  0.80 23.00
44   Outra  Mulher    [3SM]+1 a [5SM]   19975.50  0.90 19.97
45   Outra  Mulher   [5SM]+1 a [10SM]    8048.31  0.60 28.29
46   Outra  Mulher  [10SM]+1 a [20SM]    4010.68  0.70 34.02

In [97]:
df08['total_arredondado'] = df08['sum'].round()
df08['total_arredondado'] = df08['total_arredondado'].astype(int)
df08

,cor,sexo,salario,sum,prop,cv,total_arredondado
0,Branca,Homem,"1 a [0,5SM]",23742.78,12.60,16.41,23743
1,Branca,Homem,"[0,5SM]+1 a [1SM]",191383.84,10.50,5.78,191384
2,Branca,Homem,[1SM]+1 a [2SM],450445.11,13.70,4.26,450445
3,Branca,Homem,[2SM]+1 a [3SM],408520.87,16.60,4.91,408521
4,Branca,Homem,[3SM]+1 a [5SM],499566.32,22.20,3.60,499566
5,Branca,Homem,[5SM]+1 a [10SM],427637.18,32.20,4.64,427637
6,Branca,Homem,[10SM]+1 a [20SM],253229.02,45.10,6.62,253229
7,Branca,Homem,[20SM]+1 ou mais,51374.66,55.30,12.94,51375
8,Branca,Mulher,"1 a [0,5SM]",43178.97,22.90,11.47,43179
9,Branca,Mulher,"[0,5SM]+1 a [1SM]",362426.14,19.90,4.78,362426
10,Branca,Mulher,[1SM]+1 a [2SM],882258.29,26.80,2.76,882258
11,Branca,Mulher,[2SM]+1 a [3SM],749199.32,30.50,3.10,749199
12,Branca,Mulher,[3SM]+1 a [5SM],674062.68,30.00,3.28,674063
13,Branca,Mulher,[5SM]+1 a [10SM],356809.93,26.80,4.94,356810
14,Branca,Mulher,[10SM]+1 a [20SM],133304.63,23.70,7.13,133305
15,Branca,Mulher,[20SM]+1 ou mais,20705.15,22.30,30.20,20705
16,Negra,Homem,"1 a [0,5SM]",39952.92,21.20,12.94,39953
17,Negra,Homem,"[0,5SM]+1 a [1SM]",465229.41,25.50,3.62,465229
18,Negra,Homem,[1SM]+1 a [2SM],794277.18,24.20,2.60,794277
19,Negra,Homem,[2SM]+1 a [3SM],512167.98,20.80,3.79,512168
20,Negra,Homem,[3SM]+1 a [5SM],536001.01,23.90,3.19,536001
21,Negra,Homem,[5SM]+1 a [10SM],316586.44,23.80,4.97,316586
22,Negra,Homem,[10SM]+1 a [20SM],113534.15,20.20,7.29,113534
23,Negra,Homem,[20SM]+1 ou mais,13199.09,14.20,20.63,13199
24,Negra,Mulher,"1 a [0,5SM]",79813.43,42.30,9.57,79813
25,Negra,Mulher,"[0,5SM]+1 a [1SM]",782488.56,42.90,2.56,782489
26,Negra,Mulher,[1SM]+1 a [2SM],1129799.31,34.40,2.09,1129799
27,Negra,Mulher,[2SM]+1 a [3SM],751577.33,30.60,2.95,751577
28,Negra,Mulher,[3SM]+1 a [5SM],503303.14,22.40,3.52,503303
29,Negra,Mulher,[5SM]+1 a [10SM],207855.79,15.60,5.79,207856
30,Negra,Mulher,[10SM]+1 a [20SM],47745.88,8.50,12.76,47746
31,Negra,Mulher,[20SM]+1 ou mais,5390.07,5.80,28.25,5390
32,Outra,Homem,"1 a [0,5SM]",292.79,0.20,97.04,293
33,Outra,Homem,"[0,5SM]+1 a [1SM]",13066.36,0.70,24.03,13066
34,Outra,Homem,[1SM]+1 a [2SM],14774.19,0.40,25.53,14774
35,Outra,Homem,[2SM]+1 a [3SM],14400.54,0.60,34.76,14401
36,Outra,Homem,[3SM]+1 a [5SM],14224.73,0.60,30.47,14225
37,Outra,Homem,[5SM]+1 a [10SM],12280.60,0.90,32.04,12281
38,Outra,Homem,[10SM]+1 a [20SM],10018.00,1.80,36.33,10018
39,Outra,Homem,[20SM]+1 ou mais,2257.43,2.40,67.89,2257
40,Outra,Mulher,"1 a [0,5SM]",1760.60,0.90,58.69,1761
41,Outra,Mulher,"[0,5SM]+1 a [1SM]",9671.04,0.50,25.00,9671
42,Outra,Mulher,[1SM]+1 a [2SM],15384.42,0.50,19.36,15384
43,Outra,Mulher,[2SM]+1 a [3SM],20689.49,0.80,23.00,20689
44,Outra,Mulher,[3SM]+1 a [5SM],19975.50,0.90,19.97,19976
45,Outra,Mulher,[5SM]+1 a [10SM],8048.31,0.60,28.29,8048
46,Outra,Mulher,[10SM]+1 a [20SM],4010.68,0.70,34.02,4011

In [98]:
df08.columns

Index(['cor', 'sexo', 'salario', 'sum', 'prop', 'cv', 'total_arredondado'], dtype='object')

In [99]:
df08 = df08.rename(columns={'sum':'total',
                        'prop': 'proporcao',
                        'cv':'coeficiente_variacao',
                        'salario':'faixa_salarial'
                        })
df08

,cor,sexo,faixa_salarial,total,proporcao,coeficiente_variacao,total_arredondado
0,Branca,Homem,"1 a [0,5SM]",23742.78,12.60,16.41,23743
1,Branca,Homem,"[0,5SM]+1 a [1SM]",191383.84,10.50,5.78,191384
2,Branca,Homem,[1SM]+1 a [2SM],450445.11,13.70,4.26,450445
3,Branca,Homem,[2SM]+1 a [3SM],408520.87,16.60,4.91,408521
4,Branca,Homem,[3SM]+1 a [5SM],499566.32,22.20,3.60,499566
5,Branca,Homem,[5SM]+1 a [10SM],427637.18,32.20,4.64,427637
6,Branca,Homem,[10SM]+1 a [20SM],253229.02,45.10,6.62,253229
7,Branca,Homem,[20SM]+1 ou mais,51374.66,55.30,12.94,51375
8,Branca,Mulher,"1 a [0,5SM]",43178.97,22.90,11.47,43179
9,Branca,Mulher,"[0,5SM]+1 a [1SM]",362426.14,19.90,4.78,362426
10,Branca,Mulher,[1SM]+1 a [2SM],882258.29,26.80,2.76,882258
11,Branca,Mulher,[2SM]+1 a [3SM],749199.32,30.50,3.10,749199
12,Branca,Mulher,[3SM]+1 a [5SM],674062.68,30.00,3.28,674063
13,Branca,Mulher,[5SM]+1 a [10SM],356809.93,26.80,4.94,356810
14,Branca,Mulher,[10SM]+1 a [20SM],133304.63,23.70,7.13,133305
15,Branca,Mulher,[20SM]+1 ou mais,20705.15,22.30,30.20,20705
16,Negra,Homem,"1 a [0,5SM]",39952.92,21.20,12.94,39953
17,Negra,Homem,"[0,5SM]+1 a [1SM]",465229.41,25.50,3.62,465229
18,Negra,Homem,[1SM]+1 a [2SM],794277.18,24.20,2.60,794277
19,Negra,Homem,[2SM]+1 a [3SM],512167.98,20.80,3.79,512168
20,Negra,Homem,[3SM]+1 a [5SM],536001.01,23.90,3.19,536001
21,Negra,Homem,[5SM]+1 a [10SM],316586.44,23.80,4.97,316586
22,Negra,Homem,[10SM]+1 a [20SM],113534.15,20.20,7.29,113534
23,Negra,Homem,[20SM]+1 ou mais,13199.09,14.20,20.63,13199
24,Negra,Mulher,"1 a [0,5SM]",79813.43,42.30,9.57,79813
25,Negra,Mulher,"[0,5SM]+1 a [1SM]",782488.56,42.90,2.56,782489
26,Negra,Mulher,[1SM]+1 a [2SM],1129799.31,34.40,2.09,1129799
27,Negra,Mulher,[2SM]+1 a [3SM],751577.33,30.60,2.95,751577
28,Negra,Mulher,[3SM]+1 a [5SM],503303.14,22.40,3.52,503303
29,Negra,Mulher,[5SM]+1 a [10SM],207855.79,15.60,5.79,207856
30,Negra,Mulher,[10SM]+1 a [20SM],47745.88,8.50,12.76,47746
31,Negra,Mulher,[20SM]+1 ou mais,5390.07,5.80,28.25,5390
32,Outra,Homem,"1 a [0,5SM]",292.79,0.20,97.04,293
33,Outra,Homem,"[0,5SM]+1 a [1SM]",13066.36,0.70,24.03,13066
34,Outra,Homem,[1SM]+1 a [2SM],14774.19,0.40,25.53,14774
35,Outra,Homem,[2SM]+1 a [3SM],14400.54,0.60,34.76,14401
36,Outra,Homem,[3SM]+1 a [5SM],14224.73,0.60,30.47,14225
37,Outra,Homem,[5SM]+1 a [10SM],12280.60,0.90,32.04,12281
38,Outra,Homem,[10SM]+1 a [20SM],10018.00,1.80,36.33,10018
39,Outra,Homem,[20SM]+1 ou mais,2257.43,2.40,67.89,2257
40,Outra,Mulher,"1 a [0,5SM]",1760.60,0.90,58.69,1761
41,Outra,Mulher,"[0,5SM]+1 a [1SM]",9671.04,0.50,25.00,9671
42,Outra,Mulher,[1SM]+1 a [2SM],15384.42,0.50,19.36,15384
43,Outra,Mulher,[2SM]+1 a [3SM],20689.49,0.80,23.00,20689
44,Outra,Mulher,[3SM]+1 a [5SM],19975.50,0.90,19.97,19976
45,Outra,Mulher,[5SM]+1 a [10SM],8048.31,0.60,28.29,8048
46,Outra,Mulher,[10SM]+1 a [20SM],4010.68,0.70,34.02,4011

In [100]:
df08['faixa_salarial'].unique()

array(['1 a [0,5SM]', '[0,5SM]+1 a [1SM]', '[1SM]+1 a [2SM]',
       '[2SM]+1 a [3SM]', '[3SM]+1 a [5SM]', '[5SM]+1 a [10SM]',
       '[10SM]+1 a [20SM]', '[20SM]+1 ou mais'], dtype=object)

In [102]:
df08

,cor,sexo,faixa_salarial,total,proporcao,coeficiente_variacao,total_arredondado
0,Branca,Homem,"1 a [0,5SM]",23742.78,12.60,16.41,23743
1,Branca,Homem,"[0,5SM]+1 a [1SM]",191383.84,10.50,5.78,191384
2,Branca,Homem,[1SM]+1 a [2SM],450445.11,13.70,4.26,450445
3,Branca,Homem,[2SM]+1 a [3SM],408520.87,16.60,4.91,408521
4,Branca,Homem,[3SM]+1 a [5SM],499566.32,22.20,3.60,499566
5,Branca,Homem,[5SM]+1 a [10SM],427637.18,32.20,4.64,427637
6,Branca,Homem,[10SM]+1 a [20SM],253229.02,45.10,6.62,253229
7,Branca,Homem,[20SM]+1 ou mais,51374.66,55.30,12.94,51375
8,Branca,Mulher,"1 a [0,5SM]",43178.97,22.90,11.47,43179
9,Branca,Mulher,"[0,5SM]+1 a [1SM]",362426.14,19.90,4.78,362426
10,Branca,Mulher,[1SM]+1 a [2SM],882258.29,26.80,2.76,882258
11,Branca,Mulher,[2SM]+1 a [3SM],749199.32,30.50,3.10,749199
12,Branca,Mulher,[3SM]+1 a [5SM],674062.68,30.00,3.28,674063
13,Branca,Mulher,[5SM]+1 a [10SM],356809.93,26.80,4.94,356810
14,Branca,Mulher,[10SM]+1 a [20SM],133304.63,23.70,7.13,133305
15,Branca,Mulher,[20SM]+1 ou mais,20705.15,22.30,30.20,20705
16,Negra,Homem,"1 a [0,5SM]",39952.92,21.20,12.94,39953
17,Negra,Homem,"[0,5SM]+1 a [1SM]",465229.41,25.50,3.62,465229
18,Negra,Homem,[1SM]+1 a [2SM],794277.18,24.20,2.60,794277
19,Negra,Homem,[2SM]+1 a [3SM],512167.98,20.80,3.79,512168
20,Negra,Homem,[3SM]+1 a [5SM],536001.01,23.90,3.19,536001
21,Negra,Homem,[5SM]+1 a [10SM],316586.44,23.80,4.97,316586
22,Negra,Homem,[10SM]+1 a [20SM],113534.15,20.20,7.29,113534
23,Negra,Homem,[20SM]+1 ou mais,13199.09,14.20,20.63,13199
24,Negra,Mulher,"1 a [0,5SM]",79813.43,42.30,9.57,79813
25,Negra,Mulher,"[0,5SM]+1 a [1SM]",782488.56,42.90,2.56,782489
26,Negra,Mulher,[1SM]+1 a [2SM],1129799.31,34.40,2.09,1129799
27,Negra,Mulher,[2SM]+1 a [3SM],751577.33,30.60,2.95,751577
28,Negra,Mulher,[3SM]+1 a [5SM],503303.14,22.40,3.52,503303
29,Negra,Mulher,[5SM]+1 a [10SM],207855.79,15.60,5.79,207856
30,Negra,Mulher,[10SM]+1 a [20SM],47745.88,8.50,12.76,47746
31,Negra,Mulher,[20SM]+1 ou mais,5390.07,5.80,28.25,5390
32,Outra,Homem,"1 a [0,5SM]",292.79,0.20,97.04,293
33,Outra,Homem,"[0,5SM]+1 a [1SM]",13066.36,0.70,24.03,13066
34,Outra,Homem,[1SM]+1 a [2SM],14774.19,0.40,25.53,14774
35,Outra,Homem,[2SM]+1 a [3SM],14400.54,0.60,34.76,14401
36,Outra,Homem,[3SM]+1 a [5SM],14224.73,0.60,30.47,14225
37,Outra,Homem,[5SM]+1 a [10SM],12280.60,0.90,32.04,12281
38,Outra,Homem,[10SM]+1 a [20SM],10018.00,1.80,36.33,10018
39,Outra,Homem,[20SM]+1 ou mais,2257.43,2.40,67.89,2257
40,Outra,Mulher,"1 a [0,5SM]",1760.60,0.90,58.69,1761
41,Outra,Mulher,"[0,5SM]+1 a [1SM]",9671.04,0.50,25.00,9671
42,Outra,Mulher,[1SM]+1 a [2SM],15384.42,0.50,19.36,15384
43,Outra,Mulher,[2SM]+1 a [3SM],20689.49,0.80,23.00,20689
44,Outra,Mulher,[3SM]+1 a [5SM],19975.50,0.90,19.97,19976
45,Outra,Mulher,[5SM]+1 a [10SM],8048.31,0.60,28.29,8048
46,Outra,Mulher,[10SM]+1 a [20SM],4010.68,0.70,34.02,4011

In [103]:
df08.to_csv('dados8.csv', index=False, sep=',')