In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
import pandas as pd
import numpy as np
pd.set_option('display.min_rows', None)
pd.set_option('display.max_rows', None)
df_wide = pd.read_csv('IPEA_despesa_salarios_geral.csv', sep=';', encoding='utf8')
df_wide

     ano Governo Geral      Federal      Estados   municipios
0   2002           100          100          100          100
1   2003   102,0150383  93,39212138  102,7954471  109,7966505
2   2004   105,5314074   98,9115343  102,9856936  116,2855603
3   2005   114,6595726  103,7613374  114,2087032  126,6790589
4   2006   127,6559863  116,5270029  126,2375865  141,3860968
5   2007   136,4398936  125,9445171  132,8493701  152,8126808
6   2008   148,9391002  135,9546658  143,4083208  170,8496967
7   2009   159,8338541  151,3320534  151,3320534   181,598464
8   2010   170,6183844   161,432615  160,6460779  195,3294906
9   2011   178,3453457  163,4409865   168,915498  208,1792478
10  2012   187,3610287  160,8007142  178,7111112  228,1316304
11  2013   198,7338771  167,7375982  191,5983887  241,8159494
12  2014   204,3307906  170,3885993  195,5039407  253,0474815
13  2015   202,5810446  173,3041707  192,9157711  247,7202089
14  2016   200,7384124  168,4006891  188,0077799  253,7202062
15  2017   205,5282271   176,663234  191,0288555  257,5868646
16  2018   206,4961892  176,1405417  190,3846795  262,5555575
17  2019   207,5496604  175,2612205  188,7813935  269,6574035
18  2020   203,7676853   168,165617  180,5130866  276,1408265

In [3]:
df_long = df_wide.melt('ano', var_name= 'Governos',value_name = 'despesas')
df_long

     ano       Governos     despesas
0   2002  Governo Geral          100
1   2003  Governo Geral  102,0150383
2   2004  Governo Geral  105,5314074
3   2005  Governo Geral  114,6595726
4   2006  Governo Geral  127,6559863
5   2007  Governo Geral  136,4398936
6   2008  Governo Geral  148,9391002
7   2009  Governo Geral  159,8338541
8   2010  Governo Geral  170,6183844
9   2011  Governo Geral  178,3453457
10  2012  Governo Geral  187,3610287
11  2013  Governo Geral  198,7338771
12  2014  Governo Geral  204,3307906
13  2015  Governo Geral  202,5810446
14  2016  Governo Geral  200,7384124
15  2017  Governo Geral  205,5282271
16  2018  Governo Geral  206,4961892
17  2019  Governo Geral  207,5496604
18  2020  Governo Geral  203,7676853
19  2002        Federal          100
20  2003        Federal  93,39212138
21  2004        Federal   98,9115343
22  2005        Federal  103,7613374
23  2006        Federal  116,5270029
24  2007        Federal  125,9445171
25  2008        Federal  135,9546658
26  2009        Federal  151,3320534
27  2010        Federal   161,432615
28  2011        Federal  163,4409865
29  2012        Federal  160,8007142
30  2013        Federal  167,7375982
31  2014        Federal  170,3885993
32  2015        Federal  173,3041707
33  2016        Federal  168,4006891
34  2017        Federal   176,663234
35  2018        Federal  176,1405417
36  2019        Federal  175,2612205
37  2020        Federal   168,165617
38  2002        Estados          100
39  2003        Estados  102,7954471
40  2004        Estados  102,9856936
41  2005        Estados  114,2087032
42  2006        Estados  126,2375865
43  2007        Estados  132,8493701
44  2008        Estados  143,4083208
45  2009        Estados  151,3320534
46  2010        Estados  160,6460779
47  2011        Estados   168,915498
48  2012        Estados  178,7111112
49  2013        Estados  191,5983887
50  2014        Estados  195,5039407
51  2015        Estados  192,9157711
52  2016        Estados  188,0077799
53  2017        Estados  191,0288555
54  2018        Estados  190,3846795
55  2019        Estados  188,7813935
56  2020        Estados  180,5130866
57  2002     municipios          100
58  2003     municipios  109,7966505
59  2004     municipios  116,2855603
60  2005     municipios  126,6790589
61  2006     municipios  141,3860968
62  2007     municipios  152,8126808
63  2008     municipios  170,8496967
64  2009     municipios   181,598464
65  2010     municipios  195,3294906
66  2011     municipios  208,1792478
67  2012     municipios  228,1316304
68  2013     municipios  241,8159494
69  2014     municipios  253,0474815
70  2015     municipios  247,7202089
71  2016     municipios  253,7202062
72  2017     municipios  257,5868646
73  2018     municipios  262,5555575
74  2019     municipios  269,6574035
75  2020     municipios  276,1408265

In [4]:
 df_long.to_csv('IPEA_despesa_salarios_geral.csv')

In [2]:
os.chdir('G:\\Drives compartilhados\\República.org\\4. Equipes\\Dados e Comunicação\\DADOS\\415 - Repositório de Dados\\Dados para subir\\Tabelas finais\\Tratar primeira coluna e nomes ')

In [3]:
df = pd.read_csv("IPEA_despesa_salarios_geral.csv")
df

    Unnamed: 0   ano       Governos     despesas
0            0  2002  Governo Geral          100
1            1  2003  Governo Geral  102,0150383
2            2  2004  Governo Geral  105,5314074
3            3  2005  Governo Geral  114,6595726
4            4  2006  Governo Geral  127,6559863
..         ...   ...            ...          ...
71          71  2016     municipios  253,7202062
72          72  2017     municipios  257,5868646
73          73  2018     municipios  262,5555575
74          74  2019     municipios  269,6574035
75          75  2020     municipios  276,1408265

[76 rows x 4 columns]

Renomeação de coluna

In [7]:
df.rename(columns={"Governos": "governos"}, inplace=True)
df

     ano       governos     despesas
0   2002  Governo Geral          100
1   2003  Governo Geral  102,0150383
2   2004  Governo Geral  105,5314074
3   2005  Governo Geral  114,6595726
4   2006  Governo Geral  127,6559863
..   ...            ...          ...
71  2016     municipios  253,7202062
72  2017     municipios  257,5868646
73  2018     municipios  262,5555575
74  2019     municipios  269,6574035
75  2020     municipios  276,1408265

[76 rows x 3 columns]

Eliminação de coluna

In [5]:
df = df.drop('Unnamed: 0', axis=1)
df

     ano       Governos     despesas
0   2002  Governo Geral          100
1   2003  Governo Geral  102,0150383
2   2004  Governo Geral  105,5314074
3   2005  Governo Geral  114,6595726
4   2006  Governo Geral  127,6559863
..   ...            ...          ...
71  2016     municipios  253,7202062
72  2017     municipios  257,5868646
73  2018     municipios  262,5555575
74  2019     municipios  269,6574035
75  2020     municipios  276,1408265

[76 rows x 3 columns]

In [ ]:
df = df.to_csv('IPEA_despesa_salarios_geral.csv', index = False)