In [3]:
import numpy as np
import pandas as pd
import os

In [2]:
import numpy as np
import pandas as pd
import os
df_wide = pd.read_csv('RAIS_remuneracao_poder_nivel_raca_sexo.csv', sep=';', encoding='latin-1')
df_wide

FileNotFoundError: [Errno 2] No such file or directory: 'RAIS_remuneracao_poder_nivel_raca_sexo.csv'

In [6]:
df_wide.drop(df_wide.columns[df_wide.columns.str.contains('unnamed',case = False)],axis = 1, inplace = True)
df_wide

,esfera,poder,descricao_raca_ou_cor,genero,2004,2005,2006,2007,2008,2009,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Estadual,Executivo,Amarela,Feminino,4015.95,3983.14,4119.69,4312.00,4322.57,4492.78,...,4936.17,5305.54,5560.71,5794.32,5775.08,5503.35,5480.09,4901.97,4886.86,4895.20
1,Estadual,Executivo,Amarela,Masculino,5997.78,6043.90,6277.75,6496.10,6489.77,6718.81,...,6646.30,7276.20,7697.69,8155.16,8319.76,8004.46,7779.07,7090.21,6940.58,7066.89
2,Estadual,Executivo,Branca,Feminino,3697.87,3787.02,4082.49,4263.07,4324.30,4479.33,...,4818.33,5156.66,5292.44,5595.60,5585.42,5407.74,5511.69,4743.90,4685.77,4657.33
3,Estadual,Executivo,Branca,Masculino,5103.61,5307.19,5693.57,5927.51,5983.01,6157.08,...,6515.18,6937.89,7272.34,7664.44,7802.97,7581.70,7621.77,6808.76,6733.90,6638.14
4,Estadual,Executivo,Indígena,Feminino,4904.91,5484.75,6397.41,7037.36,7356.58,7551.57,...,8158.02,8570.61,8717.74,8846.57,8741.40,8228.51,8216.43,6794.73,6805.95,6533.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,Municipal,Legislativo,Indígena,Masculino,2958.51,3307.28,3518.59,3685.73,3775.54,4033.16,...,3785.69,4449.91,4968.71,4845.43,4860.72,4590.07,4497.94,3958.05,4284.68,4429.29
76,Municipal,Legislativo,Parda,Feminino,3514.17,3468.20,3634.71,3831.92,3906.65,3993.29,...,3952.67,4269.60,4317.14,4472.76,4387.58,4258.53,4347.65,3590.58,3578.90,3513.53
77,Municipal,Legislativo,Parda,Masculino,3909.52,4028.62,4196.90,4307.77,4457.05,4595.41,...,4435.91,4806.58,4764.90,4943.76,4848.61,4723.55,4716.94,3974.48,3956.51,3933.84
78,Municipal,Legislativo,Preta,Feminino,3736.59,3709.68,3870.82,3987.08,4001.62,4164.15,...,4132.10,4529.96,4486.38,4710.46,4817.21,4598.04,4787.01,4025.33,3964.74,3885.53
79,Municipal,Legislativo,Preta,Masculino,4464.84,4466.48,4593.16,4944.16,5094.74,5011.24,...,4963.21,5285.92,5351.59,5540.92,5432.34,5406.90,5405.31,4636.17,4674.41,4579.23

In [8]:
df_long = df_wide.melt(id_vars =['esfera', 'poder', 'descricao_raca_ou_cor', 'genero'], 
        value_vars =['2004', '2005','2006', '2007','2008', '2009', '2010','2011','2012','2013','2014','2015','2016','2017','2018', '2019','2020'], 
        var_name ='Anos', 
        value_name ='Valores')
df_long

         esfera        poder descricao_raca_ou_cor     genero  Anos  Valores
0      Estadual    Executivo               Amarela   Feminino  2004  4015.95
1      Estadual    Executivo               Amarela  Masculino  2004  5997.78
2      Estadual    Executivo                Branca   Feminino  2004  3697.87
3      Estadual    Executivo                Branca  Masculino  2004  5103.61
4      Estadual    Executivo              Indígena   Feminino  2004  4904.91
...         ...          ...                   ...        ...   ...      ...
1355  Municipal  Legislativo              Indígena  Masculino  2020  4429.29
1356  Municipal  Legislativo                 Parda   Feminino  2020  3513.53
1357  Municipal  Legislativo                 Parda  Masculino  2020  3933.84
1358  Municipal  Legislativo                 Preta   Feminino  2020  3885.53
1359  Municipal  Legislativo                 Preta  Masculino  2020  4579.23

[1360 rows x 6 columns]

In [13]:
df_long.rename(columns = {'esfera':'Esfera', 'poder':'Poder', 'descricao_raca_ou_cor' : 'Raça', 
                              'genero':'Gênero'}, inplace = True)
df_long

         Esfera        Poder      Raça     Gênero  Anos  Valores
0      Estadual    Executivo   Amarela   Feminino  2004  4015.95
1      Estadual    Executivo   Amarela  Masculino  2004  5997.78
2      Estadual    Executivo    Branca   Feminino  2004  3697.87
3      Estadual    Executivo    Branca  Masculino  2004  5103.61
4      Estadual    Executivo  Indígena   Feminino  2004  4904.91
...         ...          ...       ...        ...   ...      ...
1355  Municipal  Legislativo  Indígena  Masculino  2020  4429.29
1356  Municipal  Legislativo     Parda   Feminino  2020  3513.53
1357  Municipal  Legislativo     Parda  Masculino  2020  3933.84
1358  Municipal  Legislativo     Preta   Feminino  2020  3885.53
1359  Municipal  Legislativo     Preta  Masculino  2020  4579.23

[1360 rows x 6 columns]

In [1]:
df_long.to_csv('RAIS_remuneracao_poder_nivel_raca_sexo.csv')

NameError: name 'df_long' is not defined

Renomeação das colunas

In [4]:
os.chdir('G:\\Drives compartilhados\\República.org\\4. Equipes\\Dados e Comunicação\\DADOS\\415 - Repositório de Dados\\Dados para subir\\Tabelas finais')

In [11]:
df = pd.read_csv("RAIS_remuneracao_poder_nivel_raca_sexo.csv")
df

         esfera        poder      raça     gênero  anos  valores
0      Estadual    Executivo   Amarela   Feminino  2004  4015.95
1      Estadual    Executivo   Amarela  Masculino  2004  5997.78
2      Estadual    Executivo    Branca   Feminino  2004  3697.87
3      Estadual    Executivo    Branca  Masculino  2004  5103.61
4      Estadual    Executivo  Indígena   Feminino  2004  4904.91
...         ...          ...       ...        ...   ...      ...
1355  Municipal  Legislativo  Indígena  Masculino  2020  4429.29
1356  Municipal  Legislativo     Parda   Feminino  2020  3513.53
1357  Municipal  Legislativo     Parda  Masculino  2020  3933.84
1358  Municipal  Legislativo     Preta   Feminino  2020  3885.53
1359  Municipal  Legislativo     Preta  Masculino  2020  4579.23

[1360 rows x 6 columns]

In [12]:
df.rename(columns={"esfera": "esfera", "Poder": "poder", "raça" : "raca", "gênero" : "genero", "anos" : "anos", "valores" : "valores" }, inplace=True)
df

         esfera        poder      raca     genero  anos  valores
0      Estadual    Executivo   Amarela   Feminino  2004  4015.95
1      Estadual    Executivo   Amarela  Masculino  2004  5997.78
2      Estadual    Executivo    Branca   Feminino  2004  3697.87
3      Estadual    Executivo    Branca  Masculino  2004  5103.61
4      Estadual    Executivo  Indígena   Feminino  2004  4904.91
...         ...          ...       ...        ...   ...      ...
1355  Municipal  Legislativo  Indígena  Masculino  2020  4429.29
1356  Municipal  Legislativo     Parda   Feminino  2020  3513.53
1357  Municipal  Legislativo     Parda  Masculino  2020  3933.84
1358  Municipal  Legislativo     Preta   Feminino  2020  3885.53
1359  Municipal  Legislativo     Preta  Masculino  2020  4579.23

[1360 rows x 6 columns]

Eliminação da coluna

In [13]:
df = df.drop('Unnamed: 0', axis=1)
df

KeyError: "['Unnamed: 0'] not found in axis"

In [9]:
df = df.to_csv("RAIS_remuneracao_poder_nivel_raca_sexo.csv", index = False)
df