In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
import pandas as pd
import numpy as np
pd.set_option('display.min_rows', None)
pd.set_option('display.max_rows', None)
df_wide = pd.read_csv('SIAPE_proporcao_carreira_grupos.csv',  sep=';')
df_wide

,ano,social,economia_financas_gestao,infraestrutura_desenvolvimento_pesquisa,juridico_policial,apoio_tecnico_administrativo,regulacao_auditoria_fiscalizacao,nao_classificado
0,2004,0.375,0.007,0.052,0.050,0.374,0.046,0.095
1,2005,0.367,0.007,0.053,0.053,0.362,0.049,0.109
2,2006,0.383,0.008,0.060,0.058,0.342,0.055,0.093
3,2007,0.380,0.008,0.058,0.059,0.336,0.066,0.092
4,2008,0.385,0.008,0.058,0.060,0.331,0.067,0.090
5,2009,0.413,0.008,0.053,0.055,0.317,0.070,0.083
6,2010,0.425,0.008,0.053,0.054,0.312,0.069,0.080
7,2011,0.431,0.008,0.053,0.053,0.309,0.067,0.079
8,2012,0.437,0.008,0.052,0.053,0.306,0.066,0.078
9,2013,0.445,0.008,0.052,0.054,0.299,0.065,0.076
10,2014,0.451,0.008,0.051,0.053,0.299,0.063,0.075
11,2015,0.462,0.005,0.050,0.053,0.296,0.061,0.073
12,2016,0.465,0.013,0.047,0.054,0.294,0.061,0.066
13,2017,0.469,0.013,0.046,0.053,0.292,0.059,0.068

In [3]:
df_long = df_wide.melt(id_vars =['ano', 'social'], 
        value_vars =['economia_financas_gestao', 'infraestrutura_desenvolvimento_pesquisa','juridico_policial', 'apoio_tecnico_administrativo','regulacao_auditoria_fiscalizacao', 'nao_classificado'], 
        var_name ='Carreiras', 
        value_name ='Percentual')
df_long

     ano  social                                Carreiras  Percentual
0   2004   0.375                 economia_financas_gestao       0.007
1   2005   0.367                 economia_financas_gestao       0.007
2   2006   0.383                 economia_financas_gestao       0.008
3   2007   0.380                 economia_financas_gestao       0.008
4   2008   0.385                 economia_financas_gestao       0.008
5   2009   0.413                 economia_financas_gestao       0.008
6   2010   0.425                 economia_financas_gestao       0.008
7   2011   0.431                 economia_financas_gestao       0.008
8   2012   0.437                 economia_financas_gestao       0.008
9   2013   0.445                 economia_financas_gestao       0.008
10  2014   0.451                 economia_financas_gestao       0.008
11  2015   0.462                 economia_financas_gestao       0.005
12  2016   0.465                 economia_financas_gestao       0.013
13  2017   0.469                 economia_financas_gestao       0.013
14  2004   0.375  infraestrutura_desenvolvimento_pesquisa       0.052
15  2005   0.367  infraestrutura_desenvolvimento_pesquisa       0.053
16  2006   0.383  infraestrutura_desenvolvimento_pesquisa       0.060
17  2007   0.380  infraestrutura_desenvolvimento_pesquisa       0.058
18  2008   0.385  infraestrutura_desenvolvimento_pesquisa       0.058
19  2009   0.413  infraestrutura_desenvolvimento_pesquisa       0.053
20  2010   0.425  infraestrutura_desenvolvimento_pesquisa       0.053
21  2011   0.431  infraestrutura_desenvolvimento_pesquisa       0.053
22  2012   0.437  infraestrutura_desenvolvimento_pesquisa       0.052
23  2013   0.445  infraestrutura_desenvolvimento_pesquisa       0.052
24  2014   0.451  infraestrutura_desenvolvimento_pesquisa       0.051
25  2015   0.462  infraestrutura_desenvolvimento_pesquisa       0.050
26  2016   0.465  infraestrutura_desenvolvimento_pesquisa       0.047
27  2017   0.469  infraestrutura_desenvolvimento_pesquisa       0.046
28  2004   0.375                        juridico_policial       0.050
29  2005   0.367                        juridico_policial       0.053
30  2006   0.383                        juridico_policial       0.058
31  2007   0.380                        juridico_policial       0.059
32  2008   0.385                        juridico_policial       0.060
33  2009   0.413                        juridico_policial       0.055
34  2010   0.425                        juridico_policial       0.054
35  2011   0.431                        juridico_policial       0.053
36  2012   0.437                        juridico_policial       0.053
37  2013   0.445                        juridico_policial       0.054
38  2014   0.451                        juridico_policial       0.053
39  2015   0.462                        juridico_policial       0.053
40  2016   0.465                        juridico_policial       0.054
41  2017   0.469                        juridico_policial       0.053
42  2004   0.375             apoio_tecnico_administrativo       0.374
43  2005   0.367             apoio_tecnico_administrativo       0.362
44  2006   0.383             apoio_tecnico_administrativo       0.342
45  2007   0.380             apoio_tecnico_administrativo       0.336
46  2008   0.385             apoio_tecnico_administrativo       0.331
47  2009   0.413             apoio_tecnico_administrativo       0.317
48  2010   0.425             apoio_tecnico_administrativo       0.312
49  2011   0.431             apoio_tecnico_administrativo       0.309
50  2012   0.437             apoio_tecnico_administrativo       0.306
51  2013   0.445             apoio_tecnico_administrativo       0.299
52  2014   0.451             apoio_tecnico_administrativo       0.299
53  2015   0.462             apoio_tecnico_administrativo       0.296
54  2016   0.465             apoio_tecnico_administrativo       0.294
55  2017   0.469             apoio_tecnico_administrativo       0.292
56  2004   0.375         regulacao_auditoria_fiscalizacao       0.046
57  2005   0.367         regulacao_auditoria_fiscalizacao       0.049
58  2006   0.383         regulacao_auditoria_fiscalizacao       0.055
59  2007   0.380         regulacao_auditoria_fiscalizacao       0.066
60  2008   0.385         regulacao_auditoria_fiscalizacao       0.067
61  2009   0.413         regulacao_auditoria_fiscalizacao       0.070
62  2010   0.425         regulacao_auditoria_fiscalizacao       0.069
63  2011   0.431         regulacao_auditoria_fiscalizacao       0.067
64  2012   0.437         regulacao_auditoria_fiscalizacao       0.066
65  2013   0.445         regulacao_auditoria_fiscalizacao       0.065
66  2014   0.451         regulacao_auditoria_fiscalizacao       0.063
67  2015   0.462         regulacao_auditoria_fiscalizacao       0.061
68  2016   0.465         regulacao_auditoria_fiscalizacao       0.061
69  2017   0.469         regulacao_auditoria_fiscalizacao       0.059
70  2004   0.375                         nao_classificado       0.095
71  2005   0.367                         nao_classificado       0.109
72  2006   0.383                         nao_classificado       0.093
73  2007   0.380                         nao_classificado       0.092
74  2008   0.385                         nao_classificado       0.090
75  2009   0.413                         nao_classificado       0.083
76  2010   0.425                         nao_classificado       0.080
77  2011   0.431                         nao_classificado       0.079
78  2012   0.437                         nao_classificado       0.078
79  2013   0.445                         nao_classificado       0.076
80  2014   0.451                         nao_classificado       0.075
81  2015   0.462                         nao_classificado       0.073
82  2016   0.465                         nao_classificado       0.066
83  2017   0.469                         nao_classificado       0.068

In [4]:
df_long.to_csv('SIAPE_proporcao_carreira_grupos.csv')

Renomeação das tabelas

In [2]:
os.chdir('G:\\Drives compartilhados\\República.org\\4. Equipes\\Dados e Comunicação\\DADOS\\415 - Repositório de Dados\\Dados para subir\\Tabelas finais')

In [3]:
df = pd.read_csv("SIAPE_proporcao_carreira_grupos.csv")
df

    Unnamed: 0   ano  social                 Carreiras  Percentual
0            0  2004   0.375  economia_financas_gestao       0.007
1            1  2005   0.367  economia_financas_gestao       0.007
2            2  2006   0.383  economia_financas_gestao       0.008
3            3  2007   0.380  economia_financas_gestao       0.008
4            4  2008   0.385  economia_financas_gestao       0.008
..         ...   ...     ...                       ...         ...
79          79  2013   0.445          nao_classificado       0.076
80          80  2014   0.451          nao_classificado       0.075
81          81  2015   0.462          nao_classificado       0.073
82          82  2016   0.465          nao_classificado       0.066
83          83  2017   0.469          nao_classificado       0.068

[84 rows x 5 columns]

In [5]:
df.rename(columns={"Carreiras": "carreiras", "Percentual": "percentual"}, inplace = True)
df

    Unnamed: 0   ano  social                 carreiras  percentual
0            0  2004   0.375  economia_financas_gestao       0.007
1            1  2005   0.367  economia_financas_gestao       0.007
2            2  2006   0.383  economia_financas_gestao       0.008
3            3  2007   0.380  economia_financas_gestao       0.008
4            4  2008   0.385  economia_financas_gestao       0.008
..         ...   ...     ...                       ...         ...
79          79  2013   0.445          nao_classificado       0.076
80          80  2014   0.451          nao_classificado       0.075
81          81  2015   0.462          nao_classificado       0.073
82          82  2016   0.465          nao_classificado       0.066
83          83  2017   0.469          nao_classificado       0.068

[84 rows x 5 columns]

In [6]:
df = df.drop('Unnamed: 0', axis=1)
df

     ano  social                 carreiras  percentual
0   2004   0.375  economia_financas_gestao       0.007
1   2005   0.367  economia_financas_gestao       0.007
2   2006   0.383  economia_financas_gestao       0.008
3   2007   0.380  economia_financas_gestao       0.008
4   2008   0.385  economia_financas_gestao       0.008
..   ...     ...                       ...         ...
79  2013   0.445          nao_classificado       0.076
80  2014   0.451          nao_classificado       0.075
81  2015   0.462          nao_classificado       0.073
82  2016   0.465          nao_classificado       0.066
83  2017   0.469          nao_classificado       0.068

[84 rows x 4 columns]

In [ ]:
df.to_csv('SIAPE_proporcao_carreira_grupos.csv', index = False)