In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
os.chdir('G:\\Drives compartilhados\\República.org\\4. Equipes\\Dados e Comunicação\\DADOS\\415 - Repositório de Dados\\Dados para subir\\Dados Brutos\\Atlas do Estado')

In [4]:
df= pd.read_csv("SIAPE_remuneracao_liquida_executivo_sexo_raca.csv", sep=";")
df

    Unnamed: 0   ano      sexo_raça liquido
0            1  1999   Homem Branco  6527,2
1            2  1999    Homem Negro  4768,7
2            3  1999  Mulher Branca  5261,6
3            4  1999   Mulher Negra    4010
4            5  2000   Homem Branco  5690,3
..         ...   ...            ...     ...
83          84  2019   Mulher Negra  5996,2
84          85  2020   Homem Branco  8774,2
85          86  2020    Homem Negro  6272,2
86          87  2020  Mulher Branca  7753,8
87          88  2020   Mulher Negra  5815,5

[88 rows x 4 columns]

Separação da coluna "sexo_raça" em "Sexo" e "Raça"

In [6]:
df['sexo_raça'].unique() #para mostrar os valores inclusos na coluna "sexo_raça"

array(['Homem Branco', 'Homem Negro', 'Mulher Branca', 'Mulher Negra'],
      dtype=object)

In [7]:
df['Sexo'] = df['sexo_raça'].apply(lambda x: 'Feminino' if x in ['Mulher Branca','Mulher Negra','Não informado feminino','Outros Feminino'] else 'Masculino' )
#Criando uma coluna apenas para 'Sexo' contendo Feminino e Masculino, incluindo os valores corretos para cada.

In [21]:
#Em seguida, será definido na coluna "raca" os valores "branco(a)" e "negro(a)"

In [9]:
def raca (df):
    if df['sexo_raça'] in ['Homem Branco', 'Mulher Branca']:
        return 'Branco'
    elif df['sexo_raça'] in ['Homem Negro', 'Mulher Negra']:
        return 'Negro'
    elif df['sexo_raça'] in ['Não informado masculino', 'Não informado feminino']:
        return 'Não informado'
    elif df['sexo_raça'] in ['Outros Feminino', 'Outros Masculino']:
        return 'Outros'

In [22]:
df['raça'] = df.apply(raca, axis=1) #incluindo a função acima na coluna denominada "raça"
df

KeyError: 'sexo_raça'

Eliminação das colunas

In [14]:
df.drop(['sexo_raça',], axis = 1, inplace=True)
df

KeyError: "['sexo_raça'] not found in axis"

In [16]:
df.drop(['Unnamed: 0'], axis = 1, inplace=True)
df

     ano liquido       Sexo    raça
0   1999  6527,2  Masculino  Branco
1   1999  4768,7  Masculino   Negro
2   1999  5261,6   Feminino  Branco
3   1999    4010   Feminino   Negro
4   2000  5690,3  Masculino  Branco
..   ...     ...        ...     ...
83  2019  5996,2   Feminino   Negro
84  2020  8774,2  Masculino  Branco
85  2020  6272,2  Masculino   Negro
86  2020  7753,8   Feminino  Branco
87  2020  5815,5   Feminino   Negro

[88 rows x 4 columns]

In [19]:
df.rename(columns={"Sexo":"sexo","raça":"raca"}, inplace=True)
df

     ano liquido       sexo    raca
0   1999  6527,2  Masculino  Branco
1   1999  4768,7  Masculino   Negro
2   1999  5261,6   Feminino  Branco
3   1999    4010   Feminino   Negro
4   2000  5690,3  Masculino  Branco
..   ...     ...        ...     ...
83  2019  5996,2   Feminino   Negro
84  2020  8774,2  Masculino  Branco
85  2020  6272,2  Masculino   Negro
86  2020  7753,8   Feminino  Branco
87  2020  5815,5   Feminino   Negro

[88 rows x 4 columns]

In [24]:
df = df.to_csv("SIAPE_remuneracao_liquida_executivo_sexo_raca.csv", index = False)