In [ ]:
import numpy as np
import pandas as pd
import os

In [1]:
import numpy as np
import pandas as pd
df_wide = pd.read_csv('IPEA_despesas_PIB_salarios_governo.csv', sep=';', encoding='latin-1')
df_wide

     Ano Governo Geral Federal Estados Municipios
0   2002          8,9%    2,6%    3,8%       2,5%
1   2003          8,6%    2,3%    3,7%       2,6%
2   2004          8,4%    2,3%    3,5%       2,6%
3   2005          8,7%    2,3%    3,7%       2,7%
4   2006          9,0%    2,4%    3,8%       2,8%
5   2007          8,9%    2,4%    3,7%       2,8%
6   2008          9,0%    2,4%    3,7%       2,9%
7   2009          9,4%    2,6%    3,8%       3,0%
8   2010          9,1%    2,5%    3,7%       2,9%
9   2011          9,0%    2,4%    3,6%       3,0%
10  2012          9,1%    2,3%    3,7%       3,1%
11  2013          9,2%    2,3%    3,8%       3,2%
12  2014          9,3%    2,3%    3,8%       3,2%
13  2015          9,9%    2,5%    4,0%       3,4%
14  2016          9,9%    2,4%    4,0%       3,5%
15  2017         10,0%    2,5%    4,0%       3,5%
16  2018          9,8%    2,4%    3,8%       3,5%
17  2019          9,7%    2,4%    3,8%       3,5%
18  2020          9,9%    2,4%    3,7%       3,8%

In [2]:
df_long = df_wide.melt('Ano', var_name= 'Governos', value_name = 'Despesas em % PIB')
df_long

     Ano       Governos Despesas em % PIB
0   2002  Governo Geral              8,9%
1   2003  Governo Geral              8,6%
2   2004  Governo Geral              8,4%
3   2005  Governo Geral              8,7%
4   2006  Governo Geral              9,0%
..   ...            ...               ...
71  2016     Municipios              3,5%
72  2017     Municipios              3,5%
73  2018     Municipios              3,5%
74  2019     Municipios              3,5%
75  2020     Municipios              3,8%

[76 rows x 3 columns]

In [3]:
df_long.to_csv('IPEA_despesas_PIB_salarios_governo.csv')

In [3]:
os.chdir('G:\\Drives compartilhados\\República.org\\4. Equipes\\Dados e Comunicação\\DADOS\\415 - Repositório de Dados\\Dados para subir\\Tabelas finais\\Tratar primeira coluna e nomes ')

In [5]:
df = pd.read_csv("IPEA_despesas_PIB_salarios_governo.csv")
df

    Unnamed: 0   Ano       Governos Despesas em % PIB
0            0  2002  Governo Geral              8,9%
1            1  2003  Governo Geral              8,6%
2            2  2004  Governo Geral              8,4%
3            3  2005  Governo Geral              8,7%
4            4  2006  Governo Geral              9,0%
..         ...   ...            ...               ...
71          71  2016     Municipios              3,5%
72          72  2017     Municipios              3,5%
73          73  2018     Municipios              3,5%
74          74  2019     Municipios              3,5%
75          75  2020     Municipios              3,8%

[76 rows x 4 columns]

Renomeação de coluna

In [6]:
df.rename(columns={"Ano": "ano", "Governos": "governos", "Despesas em % PIB" : "despesa_PIB_percent"}, inplace=True)
df

    Unnamed: 0   ano       governos despesa_PIB_percent
0            0  2002  Governo Geral                8,9%
1            1  2003  Governo Geral                8,6%
2            2  2004  Governo Geral                8,4%
3            3  2005  Governo Geral                8,7%
4            4  2006  Governo Geral                9,0%
..         ...   ...            ...                 ...
71          71  2016     Municipios                3,5%
72          72  2017     Municipios                3,5%
73          73  2018     Municipios                3,5%
74          74  2019     Municipios                3,5%
75          75  2020     Municipios                3,8%

[76 rows x 4 columns]

Eliminação de coluna

In [8]:
df = df.drop('Unnamed: 0', axis=1)
df

     ano       governos despesa_PIB_percent
0   2002  Governo Geral                8,9%
1   2003  Governo Geral                8,6%
2   2004  Governo Geral                8,4%
3   2005  Governo Geral                8,7%
4   2006  Governo Geral                9,0%
..   ...            ...                 ...
71  2016     Municipios                3,5%
72  2017     Municipios                3,5%
73  2018     Municipios                3,5%
74  2019     Municipios                3,5%
75  2020     Municipios                3,8%

[76 rows x 3 columns]

In [ ]:
df = df.to_csv('IPEA_despesas_PIB_salarios_governo.csv', index = False)