In [12]:
import numpy as np
import pandas as pd
import os

In [13]:
import numpy as np
import pandas as pd
df_wide = pd.read_csv('RAIS_vinculo_poder_nivel_raca_sexo.csv', sep=';', encoding='latin-1')
df_wide

               ,Esfera,Poder,RaÃ§a,GÃªnero,Anos,Valores
0     0,Estadual,Executivo,Amarela,Feminino,2004,151...
1     1,Estadual,Executivo,Amarela,Masculino,2004,10...
2     2,Estadual,Executivo,Branca,Feminino,2004,1239...
3     3,Estadual,Executivo,Branca,Masculino,2004,795...
4     4,Estadual,Executivo,IndÃ­gena,Feminino,2004,1...
...                                                 ...
1355  1355,Municipal,Legislativo,IndÃ­gena,Masculino...
1356  1356,Municipal,Legislativo,Parda,Feminino,2020...
1357  1357,Municipal,Legislativo,Parda,Masculino,202...
1358  1358,Municipal,Legislativo,Preta,Feminino,2020...
1359  1359,Municipal,Legislativo,Preta,Masculino,202...

[1360 rows x 1 columns]

In [14]:
df_wide.drop(df_wide.columns[df_wide.columns.str.contains('unnamed',case = False)],axis = 1, inplace = True)
df_wide

               ,Esfera,Poder,RaÃ§a,GÃªnero,Anos,Valores
0     0,Estadual,Executivo,Amarela,Feminino,2004,151...
1     1,Estadual,Executivo,Amarela,Masculino,2004,10...
2     2,Estadual,Executivo,Branca,Feminino,2004,1239...
3     3,Estadual,Executivo,Branca,Masculino,2004,795...
4     4,Estadual,Executivo,IndÃ­gena,Feminino,2004,1...
...                                                 ...
1355  1355,Municipal,Legislativo,IndÃ­gena,Masculino...
1356  1356,Municipal,Legislativo,Parda,Feminino,2020...
1357  1357,Municipal,Legislativo,Parda,Masculino,202...
1358  1358,Municipal,Legislativo,Preta,Feminino,2020...
1359  1359,Municipal,Legislativo,Preta,Masculino,202...

[1360 rows x 1 columns]

In [ ]:
df_long = df_wide.melt(id_vars =['esfera', 'poder', 'descricao_raca_ou_cor', 'genero'], 
        value_vars =['2004', '2005','2006', '2007','2008', '2009', '2010','2011','2012','2013','2014','2015','2016','2017','2018', '2019','2020'], 
        var_name ='Anos', 
        value_name ='Valores')
df_long

In [ ]:
df_long.rename(columns = {'esfera':'Esfera', 'poder':'Poder', 'descricao_raca_ou_cor' : 'Raça', 
                              'genero':'Gênero'}, inplace = True)
df_long

         Esfera        Poder      Raça     Gênero  Anos    Valores
0      Estadual    Executivo   Amarela   Feminino  2004    15113.0
1      Estadual    Executivo   Amarela  Masculino  2004    10887.0
2      Estadual    Executivo    Branca   Feminino  2004  1239279.0
3      Estadual    Executivo    Branca  Masculino  2004   795102.0
4      Estadual    Executivo  Indígena   Feminino  2004    15046.0
...         ...          ...       ...        ...   ...        ...
1355  Municipal  Legislativo  Indígena  Masculino  2020      321.0
1356  Municipal  Legislativo     Parda   Feminino  2020    21292.0
1357  Municipal  Legislativo     Parda  Masculino  2020    25679.0
1358  Municipal  Legislativo     Preta   Feminino  2020     1953.0
1359  Municipal  Legislativo     Preta  Masculino  2020     2716.0

[1360 rows x 6 columns]

In [ ]:
df_long.to_csv('RAIS_vinculo_poder_nivel_raca_sexo.csv')

NameError: name 'df_long' is not defined

Renomeação das tabelas

In [ ]:
os.chdir('G:\\Drives compartilhados\\República.org\\4. Equipes\\Dados e Comunicação\\DADOS\\415 - Repositório de Dados\\Dados para subir\\Tabelas finais')

In [25]:
df = pd.read_csv("RAIS_vinculo_poder_nivel_raca_sexo.csv")
df

      Unnamed: 0     Esfera        Poder      Raça     Gênero  Anos    Valores
0              0   Estadual    Executivo   Amarela   Feminino  2004    15113.0
1              1   Estadual    Executivo   Amarela  Masculino  2004    10887.0
2              2   Estadual    Executivo    Branca   Feminino  2004  1239279.0
3              3   Estadual    Executivo    Branca  Masculino  2004   795102.0
4              4   Estadual    Executivo  Indígena   Feminino  2004    15046.0
...          ...        ...          ...       ...        ...   ...        ...
1355        1355  Municipal  Legislativo  Indígena  Masculino  2020      321.0
1356        1356  Municipal  Legislativo     Parda   Feminino  2020    21292.0
1357        1357  Municipal  Legislativo     Parda  Masculino  2020    25679.0
1358        1358  Municipal  Legislativo     Preta   Feminino  2020     1953.0
1359        1359  Municipal  Legislativo     Preta  Masculino  2020     2716.0

[1360 rows x 7 columns]

In [26]:
df.rename(columns={"Esfera": "esfera", "Poder": "poder", "Raça" : "raca", "Gênero" : "genero", "Anos" : "anos", "Valores" : "valores"}, inplace= True)
df

      Unnamed: 0     esfera        poder      raca     genero  anos    valores
0              0   Estadual    Executivo   Amarela   Feminino  2004    15113.0
1              1   Estadual    Executivo   Amarela  Masculino  2004    10887.0
2              2   Estadual    Executivo    Branca   Feminino  2004  1239279.0
3              3   Estadual    Executivo    Branca  Masculino  2004   795102.0
4              4   Estadual    Executivo  Indígena   Feminino  2004    15046.0
...          ...        ...          ...       ...        ...   ...        ...
1355        1355  Municipal  Legislativo  Indígena  Masculino  2020      321.0
1356        1356  Municipal  Legislativo     Parda   Feminino  2020    21292.0
1357        1357  Municipal  Legislativo     Parda  Masculino  2020    25679.0
1358        1358  Municipal  Legislativo     Preta   Feminino  2020     1953.0
1359        1359  Municipal  Legislativo     Preta  Masculino  2020     2716.0

[1360 rows x 7 columns]

Eliminação da coluna

In [27]:
df = df.drop('Unnamed: 0', axis=1)
df

         esfera        poder      raca     genero  anos    valores
0      Estadual    Executivo   Amarela   Feminino  2004    15113.0
1      Estadual    Executivo   Amarela  Masculino  2004    10887.0
2      Estadual    Executivo    Branca   Feminino  2004  1239279.0
3      Estadual    Executivo    Branca  Masculino  2004   795102.0
4      Estadual    Executivo  Indígena   Feminino  2004    15046.0
...         ...          ...       ...        ...   ...        ...
1355  Municipal  Legislativo  Indígena  Masculino  2020      321.0
1356  Municipal  Legislativo     Parda   Feminino  2020    21292.0
1357  Municipal  Legislativo     Parda  Masculino  2020    25679.0
1358  Municipal  Legislativo     Preta   Feminino  2020     1953.0
1359  Municipal  Legislativo     Preta  Masculino  2020     2716.0

[1360 rows x 6 columns]

In [28]:
df = df.to_csv('RAIS_vinculo_poder_nivel_raca_sexo.csv', index = False)
df