In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
os.chdir('G:\\Drives compartilhados\\República.org\\4. Equipes\\Dados e Comunicação\\DADOS\\415 - Repositório de Dados\\Dados para subir\\Dados Brutos\\Atlas do Estado')

In [5]:
df= pd.read_csv("SIAPE_ativos_infraestrutura.csv", sep=";")
df

,ano,ministerios,servidores_ativos_ministerios,total_servidores_ativos,perc_servidores
0,1999,"ministerio da industria, comercio exterior e s...",2511,482854,0.52
1,1999,ministerio da integracao nacional,3025,482854,0.63
2,1999,ministerio das comunicacoes,1094,482854,0.23
3,1999,ministerio de minas e energia,2218,482854,0.46
4,1999,ministerio do meio ambiente,5957,482854,1.23
...,...,...,...,...,...
129,2018,ministerio da integracao nacional,2380,611916,0.39
130,2018,ministerio das cidades,405,611916,0.07
131,2018,ministerio de minas e energia,4097,611916,0.67
132,2018,ministerio do meio ambiente,8771,611916,1.43
133,2018,"ministerio dos transportes, portos e aviacao c...",6365,611916,1.04

In [6]:
df= df.to_csv("SIAPE_ativos_infraestrutura.csv", index=False)