In [1]:
##importando pacotes
import pandas as pd
import numpy as np
import time
import os
import pandas_gbq
from google.cloud import bigquery
import glob
import openpyxl
import csv
import re

In [2]:
os.chdir('G:\\Drives compartilhados\\República.org\\4. Equipes\\Dados e Comunicação\\DADOS E CONHECIMENTO\\415 - Repositório de Dados\\Repositório Local\\Documentos auxiliares')

In [15]:
df = pd.read_csv('ipca.csv', sep=';', encoding='UTF-8', decimal=",")
df

     Ano  IPCA acumulado dez/ano           It  Fator de correcao
0   1995                   22.41  1000.000000           5.202936
1   1996                    9.56  1095.600000           4.748938
2   1997                    5.22  1152.790320           4.513341
3   1998                    1.65  1171.811360           4.440080
4   1999                    8.94  1276.571296           4.075711
5   2000                    5.97  1352.782602           3.846099
6   2001                    7.67  1456.541028           3.572118
7   2002                   12.53  1639.045619           3.174369
8   2003                    9.30  1791.476861           2.904272
9   2004                    7.60  1927.629103           2.699138
10  2005                    5.69  2037.311199           2.553825
11  2006                    3.14  2101.282770           2.476076
12  2007                    4.46  2194.999982           2.370358
13  2008                    5.90  2324.504981           2.238299
14  2009                    4.31  2424.691145           2.145814
15  2010                    5.91  2567.990392           2.026073
16  2011                    6.50  2734.909768           1.902416
17  2012                    5.84  2894.628498           1.797445
18  2013                    5.91  3065.701042           1.697144
19  2014                    6.41  3262.212479           1.594910
20  2015                   10.67  3610.290550           1.441141
21  2016                    6.29  3837.377826           1.355857
22  2017                    2.95  3950.580472           1.317005
23  2018                    3.75  4098.727240           1.269403
24  2019                    4.31  4275.382384           1.216952
25  2020                    4.52  4468.629667           1.164325
26  2021                   10.06  4918.173812           1.057900
27  2022                    5.79  5202.936076           1.000000

In [5]:
client = bigquery.Client()

In [6]:
dataset_ref = client.dataset('Datalake')

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ano                     28 non-null     int64
 1   acumulado_dezembro_ano  28 non-null     float64
 2   it                      28 non-null     float64
 3   fator_correcao          28 non-null     float64
dtypes: float64(3), int64(1)
memory usage: 1.0 KB

In [17]:
df=df.rename(columns={"Ano":'ano','IPCA acumulado dez/ano':'acumulado_dezembro_ano','It':'it','Fator de correcao':'fator_correcao'})

In [22]:
schema = [bigquery.SchemaField('ano', 'INTEGER', description= 'Ano de referência da observação'),
          bigquery.SchemaField('acumulado_dezembro_ano', 'FLOAT', description= 'IPCA acumulado no mês de dezembro daquele ano'),
          bigquery.SchemaField('it', 'FLOAT', description= 'indice'),
          bigquery.SchemaField('fator_correcao', 'FLOAT', description= 'Fator de correção')
]

In [23]:
table_ref = dataset_ref.table('ipca')
job_config = bigquery.LoadJobConfig(schema=schema)
job = client.load_table_from_dataframe(df, table_ref, job_config=job_config)
job.result()

LoadJob<project=repositoriodedadosgpsp, location=US, id=2e54b1c3-b70e-44ba-9600-c43807205118>